name: Deploy

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  DIRECTORY: /home/${{ secrets.SSH_USERNAME }}/whattowatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create .env files from secrets
        run: |
          echo "${{ secrets.ENV_FILE_CONTENT }}" > .env
        
      - name: Push files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: ${{ env.DIRECTORY }}

      - name: Start project
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Change directory
            cd ${{ env.DIRECTORY }}

            # Stop docker compose
            docker compose down

            # Run docker compose
            docker compose up -d --build

