name: Deploy

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  DIRECTORY: ~/whattowatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create .env files from secrets
        run: |
          echo "${{ secrets.ENV_FILE_CONTENT }}" > .env
        
      - name: Push files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: ${{ env.DIRECTORY }}
          timeout: 120s

      - name: Start project
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Change directory
            cd ${{ env.DIRECTORY }}

            # Build docker images
            docker compose build

            # Restart docker compose
            docker compose down
            docker compose up -d

